title: Electronics Section
description: Official Blog
author: Electronics Section
logo: /static/img/avatar.png
github_url: https://github.com/ecsectioniitr/
about: IIT Roorkee
repository: ecsectioniitr/ecsectioniitr.github.io

baseurl: ""
url: "http://ecsectioniitr.ml"

disqus_shortname: ecsection
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, jekyll-github-metadata]